### ISSUE TITLE
Improvements: Replace this.state.open in HotelFilter with pure css

### ISSUE THREAD

**Issue by Olie440** [Olie440/lateroom-techtest#12]
In `hotel-filter.component.js` I have created a class component so that I can use `this.state`. This could possibly be replaced with a pure css:
```css
.hotel-filter__menu {
    display:none
}

.hotel-filter:focus-within .hotel-filter__menu {
    display: block;
}
```
